### ISSUE TITLE
View instead of a listview

### ISSUE THREAD

**Issue by cavessa** [jc888/TiParallaxHeader#1]
Hello, 

the module is really great. Thank you.

There is also a possibility to use a View instead of a ListView. If I change that comes an error. 

greeting

**Comment by jc888** [comment]
Hi
This module probably is not the best fit for you, your best bet, would be to modify Titanium's TandemScroll view module https://github.com/appcelerator/titanium_modules/tree/master/tandemscroll

Thanks
James
